### ISSUE TITLE
mainliao can't use anymore

### ISSUE THREAD

**Issue by helloqiu** [pandada8/MiscScript#1]
I test it but it doesn't work.QAQ

**Comment by pandada8** [comment]
最近我呆在寝室比较多
过段时间我拆面聊的apk看下

**Comment by helloqiu** [comment]
好哒^_^

**Comment by helloqiu** [comment]
I hack the mianliao.apk but I can't find the codes about login to the Internet and it's very disgusting to read codes hacked.
全靠你了潘dada.QAQ

**Comment by helloqiu** [comment]
代码一团糟，估计只有抓包一条路了。
然而我并不会，拯救全校吧 @pandada8 \QAQ/\QAQ/

**Comment by pandada8** [comment]
面聊已经更新了线上程序，目前为自签的HTTPS证书，验证逻辑与以前似乎没有区别

**Comment by helloqiu** [comment]
ok
面聊的网络虽然能连接上但是还是很慢﻿T_T
所以凑合用吧。
